SELECT
    a.id,
    a.Identifier,
    a.Service,
    a.Type,
    a.Region,
    COALESCE(d.name, a.Tag_Name) helpful_string,
    COALESCE(d.action, a.Tag_Action) Tag_Action,
    COALESCE(a.Tag_Name, d.name) Tag_Name,
    COALESCE(d.application, a.Tag_Application) Tag_Application,
    COALESCE(d.brand, a.Tag_Brand) Tag_Brand,
    COALESCE(d.department, a.Tag_Department) Tag_Department,
    COALESCE(d.environment, a.Tag_Environment) Tag_Environment,
    COALESCE(d.managed, a.Tag_Managed) Tag_Managed,
    a.Tag_QuickSetupID,
    a.Tag_QuickSetupType,
    a.Tag_QuickSetupVersion,
    a.Tag_SFTP_ryan,
    a.Tag_Team,
    a.Tag_Terraform,
    a.Tag_alpha_eksctl_io_cluster_oidc_enabled,
    a.Tag_aws_chalice,
    a.Tag_aws_autoscaling_groupName,
    a.Tag_aws_cloudformation_logical_id,
    a.Tag_aws_cloudformation_stack_id,
    a.Tag_aws_cloudformation_stack_name,
    a.Tag_aws_dlm_expirationTime,
    a.Tag_aws_dlm_lifecycle_policy_id,
    a.Tag_aws_dlm_lifecycle_schedule_name,
    a.Tag_aws_ec2_fleet_id,
    a.Tag_aws_ec2launchtemplate_id,
    a.Tag_aws_ec2launchtemplate_version,
    a.Tag_aws_eks_cluster_name,
    a.Tag_description,
    a.Tag_dlm_managed,
    a.Tag_eks,
    a.Tag_eks_cluster_name,
    a.Tag_eks_nodegroup_name,
    a.Tag_env,
    a.Tag_family,
    a.Tag_instance_id,
    a.Tag_k8s_io_cluster_autoscaler_eks_common_production,
    a.Tag_k8s_io_cluster_autoscaler_eks_development,
    a.Tag_k8s_io_cluster_autoscaler_eks_production,
    a.Tag_k8s_io_cluster_autoscaler_eks_synd,
    a.Tag_k8s_io_cluster_autoscaler_enabled,
    a.Tag_k8s_io_cluster_autoscaler_nithin,
    a.Tag_kubernetes_io_cluster_eks_common_production,
    a.Tag_kubernetes_io_cluster_eks_development,
    a.Tag_kubernetes_io_cluster_eks_production,
    a.Tag_kubernetes_io_cluster_eks_synd,
    a.Tag_kubernetes_io_cluster_nithin,
    a.Tag_kubernetes_io_created_for_pv_name,
    a.Tag_kubernetes_io_created_for_pvc_name,
    a.Tag_kubernetes_io_created_for_pvc_namespace,
    a.Tag_kubernetes_io_role_elb,
    a.Tag_kubernetes_io_service_name,
    a.Tag_lambda_console_blueprint,
    a.Tag_map_migrated,
    a.Tag_ryan,
    a.Tag_serverlessrepo_applicationId,
    a.Tag_serverlessrepo_semanticVersion,
    a.Tag_sftp,
    a.Tag_shareAndCopy,
    a.Tag_site,
    a.Tag_timestamp,
    a.Tag_workload_type,
    a.Tags,
    a.ARN,
    a.Import,
    a.Tag
FROM taggables a
LEFT JOIN tagged d ON
    a.id=d.id
WHERE Type IN ('Instance','Cluster','DBInstance','Bucket')

